"use client";
import * as React from "react";
import { MOCK_ATTEMPTS, SCENARIOS } from "../lib/scenarios.ts";
import type { Decision } from "../lib/types.ts";
import { Header, Footer, Icon, DecisionBadge, ResultView } from "./ui.tsx";
interface State { filter: "all" | Decision; query: string; selected: string | null }
export class AdminDashboard extends React.Component<Record<string, never>, State> {
  state: State = { filter: "all", query: "", selected: null };
  render() {
    const { filter, query, selected } = this.state;
    const rows = MOCK_ATTEMPTS.filter(row => (filter === "all" || row.result.decision === filter) && `${row.id} ${row.scenario} ${SCENARIOS.find(s => s.id === row.scenario)!.title}`.toLowerCase().includes(query.toLowerCase().trim()));
    const selectedRow = MOCK_ATTEMPTS.find(row => row.id === selected);
    const counts = [MOCK_ATTEMPTS.length, ...(["approve", "step-up", "reject"] as const).map(d => MOCK_ATTEMPTS.filter(row => row.result.decision === d).length)];
    return <><Header active="admin" /><main id="main-content" className="dashboard page-width"><div className="page-heading"><div><span className="eyebrow">OPERATIONS / DEMO WORKSPACE</span><h1>A clearer view of every decision.</h1><p>Inspect the signals behind a fictional verification queue.</p></div><a className="button button-primary" href="/verify/">New verification<Icon name="arrow" size={17} /></a></div>
      <div className="notice notice-amber dashboard-notice"><Icon name="info" size={18} /><p><strong>Sample data only. This is not a live admin system.</strong> All attempts, times, and scores below are fixed mock fixtures. Actual webcam sessions are not saved here. No authentication or real user data is present.</p></div>
      <section className="kpi-grid" aria-label="Mock dataset totals">{["Sample attempts", "Approve", "Step-up", "Reject"].map((label, i) => <article className={`kpi-card kpi-${i}`} key={label}><div><span>{label}</span><Icon name={i === 0 ? "activity" : i === 1 ? "check" : i === 2 ? "layers" : "shield"} size={19} /></div><strong>{counts[i].toString().padStart(2, "0")}</strong><p>{i === 0 ? "Fixed fictional dataset" : "Illustrative policy decisions"}</p></article>)}</section>
      <div className="dashboard-grid"><section className="panel attempts-panel"><div className="attempts-heading"><div><h2>Verification attempts</h2><span className="microcopy">Mock timeline &middot; 05 Oct 2026 &middot; UTC</span></div><span className="dataset-badge"><span className="dot dot-amber" />MOCK DATA</span></div><div className="table-toolbar"><div className="filter-tabs" aria-label="Filter decisions">{(["all", "approve", "step-up", "reject"] as const).map(option => <button key={option} className={filter === option ? "filter-selected" : ""} onClick={() => this.setState({ filter: option })} aria-pressed={filter === option}>{option === "all" ? "All attempts" : option === "step-up" ? "Step-up" : option[0].toUpperCase() + option.slice(1)}</button>)}</div><label className="search-box"><Icon name="search" size={16} /><span className="sr-only">Search mock attempt ID or scenario</span><input value={query} onChange={e => this.setState({ query: e.target.value })} placeholder="Search attempts" /></label></div><div className="table-scroll"><table className="attempt-table"><thead><tr><th>Attempt / time</th><th>Scenario</th><th>Risk index</th><th>Decision</th><th><span className="sr-only">Inspect</span></th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className={row.id === selected ? "row-selected" : ""}><td><strong className="mono">{row.id}</strong><span className="table-time">{row.time}</span></td><td><span className={`table-scenario-icon scenario-icon-${row.scenario}`}><Icon name={row.scenario === "normal" ? "shield" : row.scenario === "virtual" ? "camera" : row.scenario === "replay" ? "play" : "scan"} size={15} /></span>{SCENARIOS.find(s => s.id === row.scenario)!.title}</td><td><div className="table-risk"><span className={`mini-risk mini-${row.result.decision}`}><i style={{ width: `${row.result.risk}%` }} /></span><span className="mono">{row.result.risk}<small>/100</small></span></div></td><td><DecisionBadge decision={row.result.decision} /></td><td><button className="icon-button" aria-label={`Inspect ${row.id}`} onClick={() => this.setState({ selected: selected === row.id ? null : row.id })}><Icon name="chevron" size={17} /></button></td></tr>)}</tbody></table></div>{rows.length === 0 && <div className="empty-table"><Icon name="search" size={26} /><h3>No matching fixtures.</h3><p>Try another attempt ID or remove the decision filter.</p><button className="button button-secondary" onClick={() => this.setState({ query: "", filter: "all" })}>Reset filters</button></div>}<div className="table-footer"><span>Showing {rows.length} of {MOCK_ATTEMPTS.length} mock attempts</span><span>Nothing here is a measured detection rate.</span></div></section>
      <aside className="dashboard-sidebar"><section className="panel policy-card"><span className="eyebrow">POLICY / V0.1</span><h2>Simple enough<br />to inspect.</h2><p>Fixed weights, visible sources, conservative handling of missing evidence.</p><div className="policy-range"><span><i className="dot" />Approve</span><strong>0 &ndash; &lt;30</strong></div><div className="policy-range"><span><i className="dot dot-amber" />Step-up</span><strong>30 &ndash; &lt;65</strong></div><div className="policy-range"><span><i className="dot dot-red" />Reject</span><strong>65 &ndash; 100</strong></div><p className="microcopy">These are demo thresholds, not fraud probabilities. Missing evidence and virtual-camera flags can veto approval. Live sessions always require another trusted check.</p><a className="text-link" href="/verify/?mode=lab">Test the policy<Icon name="arrow" size={16} /></a></section><section className="panel roadmap-card"><span className="icon-box"><Icon name="lock" /></span><h3>No biometric database.</h3><p>The real webcam flow is isolated from this dashboard. Closing or refreshing the page discards the session.</p><span className="source-badge source-simulated">Admin backend not built</span></section></aside></div>
      {selectedRow && <section className="inspector" aria-label={`Mock details for ${selectedRow.id}`}><div className="section-heading"><h2>Inspecting {selectedRow.id}</h2><button className="button button-secondary" onClick={() => this.setState({ selected: null })}><Icon name="close" size={16} />Close details</button></div><ResultView result={selectedRow.result} sessionLabel={selectedRow.id} compact /></section>}
    </main><Footer /></>;
  }
}
