import * as React from "react";
import { Header, Footer, Icon, SourceBadge, signalIcons } from "./ui.tsx";
import { SIGNALS } from "../lib/risk.ts";
const sourceLinks = {
  entrust: "https://www.entrust.com/company/newsroom/deepfakes-social-engineering-and-injection-attacks-on-the-rise",
  pindrop: "https://www.pindrop.com/company-news/deepfakes-are-hitting-the-enterprise-but-90-lack-purpose-built-defenses",
  gartner: "https://www.gartner.com/en/newsroom/press-releases/2024-02-01-gartner-predicts-30-percent-of-enterprises-will-consider-identity-verification-and-authentication-solutions-unreliable-in-isolation-due-to-deepfakes-by-2026",
};
export function Home() {
  return <><Header /><main id="main-content">
    <section className="hero page-width"><div className="hero-copy"><div className="eyebrow pill-eyebrow"><span className="dot" />IDENTITY, BEYOND APPEARANCE</div><h1>Trust the person.<br /><span>Not just the pixels.</span></h1><p className="hero-description">A convincing face is no longer enough. Aegis combines camera signals, live challenges, and light response into one explainable verification decision.</p><div className="hero-actions"><a className="button button-primary button-large" href="/verify/">Start verification<Icon name="arrow" /></a><a className="button button-secondary button-large" href="/verify/?mode=lab"><Icon name="play" size={17} />Explore attack lab</a></div><div className="hero-reassurance"><span><Icon name="lock" size={15} />On-device processing</span><span><Icon name="code" size={15} />Clearly labeled simulations</span></div></div>
    <div className="hero-visual" aria-label="Illustration of the five-signal verification stack, not a real session"><div className="visual-grid" /><div className="visual-topline"><span className="mono">AEGIS / PRESENCE ENGINE</span><span className="live-outline"><span className="dot" />CONCEPT PREVIEW</span></div><div className="shield-orbit"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="hero-shield"><Icon name="shield" size={82} /></div><span className="orbit-node node-camera"><Icon name="camera" /></span><span className="orbit-node node-eye"><Icon name="eye" /></span><span className="orbit-node node-light"><Icon name="sun" /></span></div><div className="stack-card"><div className="stack-card-header"><span>Defense in depth</span><span className="microcopy">5 signal layers</span></div>{SIGNALS.map((signal, i) => <div className="stack-row" key={signal.id}><Icon name={signalIcons[i]} size={16} /><span>{signal.title}</span><SourceBadge source={i < 3 ? "heuristic" : "simulated"} /></div>)}<div className="stack-card-footer"><Icon name="layers" size={15} /><span>Combined evidence. Explicit uncertainty.</span></div></div><span className="visual-caption">An interface demonstration, not a detection benchmark.</span></div></section>
    <section className="problem-section page-width" aria-labelledby="problem-title"><div className="problem-heading"><div><span className="eyebrow">THE PROBLEM</span><h2 id="problem-title">Seeing is no longer believing.</h2></div><p>Deepfakes target the trust behind identity checks.<br />The numbers describe the threat, not our accuracy.</p></div><div className="stat-grid"><article className="stat-card"><strong>40<span>%</span><Icon name="arrow" size={26} className="stat-arrow" /></strong><p>Year-over-year rise in digital injection attacks.</p><a href={sourceLinks.entrust} target="_blank" rel="noreferrer">Entrust, 2026 report <span>(published Nov 2025)</span><Icon name="arrow" size={14} /></a></article><article className="stat-card"><strong>74<span>%</span></strong><p>Of surveyed security leaders encountered or suspected a deepfake attack in the past year.</p><a href={sourceLinks.pindrop} target="_blank" rel="noreferrer">Pindrop, Sep 2026 <span>&middot; 250 US leaders</span><Icon name="arrow" size={14} /></a></article><article className="stat-card"><strong>30<span>%</span></strong><p>Of enterprises predicted to distrust identity verification in isolation by 2026.</p><a href={sourceLinks.gartner} target="_blank" rel="noreferrer">Gartner, Feb 2024 <span>&middot; forecast, not outcome</span><Icon name="arrow" size={14} /></a></article></div></section>
    <section className="how-section page-width"><div className="section-intro"><span className="eyebrow">A LAYERED APPROACH</span><h2>Don't ask one signal<br />to carry all the trust.</h2><p>Aegis tests different aspects of a session, exposes uncertainty, and asks for more evidence when a check is missing.</p><a className="text-link" href="/verify/">See the verification flow<Icon name="arrow" size={18} /></a></div><div className="how-steps"><article><span className="step-number">01</span><div><h3>Inspect the source</h3><p>Read camera labels and capture settings. Flag anomalies without claiming that metadata proves a camera is genuine.</p></div><Icon name="camera" /></article><article><span className="step-number">02</span><div><h3>Challenge the moment</h3><p>Random head turns, blinks, and digit prompts. Optional slow screen colors test a rough facial-light response.</p></div><Icon name="eye" /></article><article><span className="step-number">03</span><div><h3>Explain the decision</h3><p>Combine explicit weights, show every signal's origin, and never turn a missing check into an automatic pass.</p></div><Icon name="layers" /></article></div></section>
    <section className="home-bottom page-width"><div><span className="eyebrow">BUILT TO BE QUESTIONED</span><h2>Try the person.<br />Then try the attack.</h2><p>Four simulated scenarios. Three possible decisions.<br />No inflated accuracy claims.</p></div><a className="button button-light button-large" href="/verify/?mode=lab">Open the attack lab<Icon name="arrow" /></a><div className="bottom-orb" aria-hidden="true"><Icon name="scan" size={120} /></div></section>
    <div className="home-disclaimer page-width"><Icon name="info" size={17} /><p>Frontend prototype only. Deepfake and audio-visual models are simulated. Camera-derived checks are unvalidated and share failure modes. A live session cannot grant access or establish identity.</p></div>
    </main><Footer /></>;
}
